import type { TagDefinition } from '../tag-types';

export const FANTASY_CLUSTER: TagDefinition[] = [
  { tagName: 'Magic', type: 'primary', mappings: [{ traitId: 'fantasy', weight: 5 }, { traitId: 'magic_system', weight: 5 }] },
  { tagName: 'Witch', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'magic_system', weight: 3 }, { traitId: 'supernatural', weight: 2 }] },
  { tagName: 'Alchemy', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'magic_system', weight: 3 }] },
  { tagName: 'Summoning', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'summons', weight: 4 }, { traitId: 'action', weight: 2 }] },
  { tagName: 'Necromancy', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'necromancy', weight: 5 }, { traitId: 'horror', weight: 3 }, { traitId: 'dark', weight: 3 }] },
  { tagName: 'Curse', type: 'structural', mappings: [{ traitId: 'supernatural', weight: 4 }, { traitId: 'fantasy', weight: 3 }, { traitId: 'curses', weight: 5 }, { traitId: 'horror', weight: 2 }, { traitId: 'dark', weight: 2 }] },
  { tagName: 'Exorcism', type: 'structural', mappings: [{ traitId: 'supernatural', weight: 5 }, { traitId: 'exorcism', weight: 5 }, { traitId: 'horror', weight: 3 }, { traitId: 'mystery', weight: 2 }] },
  { tagName: 'Youkai', type: 'structural', mappings: [{ traitId: 'supernatural', weight: 4 }, { traitId: 'youkai', weight: 5 }, { traitId: 'fantasy', weight: 3 }, { traitId: 'historical', weight: 2 }] },
  { tagName: 'Demons', type: 'structural', mappings: [{ traitId: 'supernatural', weight: 4 }, { traitId: 'demons', weight: 5 }, { traitId: 'fantasy', weight: 3 }, { traitId: 'dark', weight: 2 }, { traitId: 'horror', weight: 2 }] },
  { tagName: 'Angels', type: 'structural', mappings: [{ traitId: 'supernatural', weight: 3 }, { traitId: 'angels', weight: 5 }, { traitId: 'fantasy', weight: 3 }, { traitId: 'gods', weight: 2 }] },
  { tagName: 'Gods', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 3 }, { traitId: 'gods', weight: 5 }, { traitId: 'epic', weight: 2 }] },
  { tagName: 'Mythology', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'gods', weight: 3 }, { traitId: 'historical', weight: 2 }, { traitId: 'epic', weight: 2 }] },
  { tagName: 'Dragons', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'adventure', weight: 2 }, { traitId: 'epic', weight: 2 }] },
  { tagName: 'Fairy Tale', type: 'flavor', mappings: [{ traitId: 'fantasy', weight: 3 }, { traitId: 'wholesome', weight: 2 }] },
  { tagName: 'Isekai', type: 'primary', mappings: [{ traitId: 'fantasy', weight: 5 }, { traitId: 'isekai', weight: 5 }, { traitId: 'adventure', weight: 3 }] },
  { tagName: 'Reverse Isekai', type: 'primary', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'isekai', weight: 4 }, { traitId: 'comedy', weight: 2 }, { traitId: 'modern_urban', weight: 2 }] },
  { tagName: 'Reincarnation', type: 'primary', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'isekai', weight: 3 }, { traitId: 'existential', weight: 1 }] },
  { tagName: 'Dungeon', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'rpg_mechanics', weight: 4 }, { traitId: 'adventure', weight: 3 }] },
  { tagName: 'Leveling', type: 'structural', mappings: [{ traitId: 'rpg_mechanics', weight: 5 }, { traitId: 'skill_trees', weight: 4 }, { traitId: 'training_loop', weight: 4 }] },
  { tagName: 'Cultivation', type: 'primary', mappings: [{ traitId: 'cultivation', weight: 5 }, { traitId: 'cultivation_power', weight: 5 }, { traitId: 'fantasy', weight: 4 }, { traitId: 'training_loop', weight: 4 }, { traitId: 'martial_arts', weight: 3 }] },
  { tagName: 'Wuxia', type: 'primary', mappings: [{ traitId: 'martial_arts', weight: 5 }, { traitId: 'cultivation_power', weight: 4 }, { traitId: 'fantasy', weight: 3 }, { traitId: 'historical', weight: 2 }] },
  { tagName: 'Monster Taming', type: 'structural', mappings: [{ traitId: 'monster_taming', weight: 5 }, { traitId: 'fantasy', weight: 4 }, { traitId: 'adventure', weight: 3 }] },
  { tagName: 'Shapeshifting', type: 'flavor', mappings: [{ traitId: 'fantasy', weight: 3 }, { traitId: 'supernatural', weight: 3 }, { traitId: 'transformation', weight: 3 }] },
  { tagName: 'Urban Fantasy', type: 'structural', mappings: [{ traitId: 'fantasy', weight: 4 }, { traitId: 'modern_urban', weight: 4 }, { traitId: 'supernatural', weight: 3 }] },
  { tagName: 'Dark Fantasy', type: 'primary', mappings: [{ traitId: 'fantasy', weight: 5 }, { traitId: 'dark', weight: 4 }, { traitId: 'grim', weight: 3 }] },
  { tagName: 'High Fantasy', type: 'primary', mappings: [{ traitId: 'fantasy', weight: 5 }, { traitId: 'fantasy_medieval', weight: 4 }, { traitId: 'epic', weight: 3 }] },
];
